[package]
name = "racegate"
version = "0.1.0"
authors = ["Alessandro Pezzato <alessandro@pezzato.net>"]
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
serde = { version = "1.0.160", features = ["serde_derive"] }

[dev-dependencies]
test-log = "0.2"
env_logger = "0.10.0"
insta = "1.29.0"
