[build]
target = "index.html"
release = true
dist = "dist"
public_url = "/"
filehash = false

[watch]
watch = []
ignore = []

[serve]
address = "127.0.0.1"
port = 8080
open = false
no_autoreload = false

[clean]
dist = "dist"
cargo = false
