#!/usr/bin/env bash

flash() {
  local platform="${1}"
  local serial="${2}"
  local address="${3}"

  local wifi_default_pass="demo"
  local wifi_default_ssid="demo"

  if [ -z "${DEMO_WIFI_CONFIG}" ]; then
    # Unless wifi configuration is overridden by env var
    local wifi_ap_enabled="false"
    if [ "${address}" == "0" ]; then
      # Enable AP
      wifi_ap_enabled="true"
    fi

    DEMO_WIFI_CONFIG="${wifi_ap_enabled}:${wifi_default_ssid}:${wifi_default_pass}"
  fi

  DEMO_NODE_ADDRESS="${address}"

  export DEMO_NODE_ADDRESS
  export DEMO_WIFI_CONFIG

  echo "DEMO_NODE_ADDRESS=${DEMO_NODE_ADDRESS}"
  echo "DEMO_WIFI_CONFIG=${DEMO_WIFI_CONFIG}"

  cargo espflash \
    --features="${platform}" \
    --speed 1500000 \
    --monitor "${serial}" \
    --partition-table partitions/partitions_singleapp_4MB.csv
}

main() {
  case $1 in
  flash) flash "${2}" "${3}" "${4}";;
  esac
}

main "$@"
